MasterFacilityList/mfl_admin_web

src/app/app.js
src/app/common/directives/actionbar.js
src/app/facilities/controllers.js
src/app/facilities/modules.js
src/app/facilities/routes.js
src/app/facilities/tpls/index.tpl.html
src/app/facilities/tpls/main.tpl.html
src/app/facilities/tpls/new_facility.tpl.html
src/app/home/tpls/index.tpl.html
src/app/home/tpls/side_nav.tpl.html
src/assets/css/theme.css
src/less/action_btn.less
src/less/basic.less
src/less/card.less
src/less/main.less
src/less/menu_cards.less
src/less/notifications.less

Putting up page for listing facilities and scafolding UI workflow for adding a new facility

Facilities

---

src/app/app.js
src/app/common/directives/actionbar.js
src/app/facilities/controllers.js
src/app/facilities/modules.js
src/app/facilities/routes.js
src/app/facilities/services.js
src/app/facilities/tpls/basic_data.tpl.html
src/app/facilities/tpls/facilities_action.tpl.html
src/app/facilities/tpls/index.tpl.html
src/app/facilities/tpls/new_facility.tpl.html
src/app/home/tpls/index.tpl.html
src/app/home/tpls/side_nav.tpl.html
src/less/action_btn.less
src/less/basic.less
src/less/card.less
src/less/form_tab.less
src/less/login.less
src/less/normal_inputs.less
src/less/theme.less

Adding scafolding for add new and edit facility as well UI for processing a facility (approving, rejecting)

New facility

---

.jshintrc
bower.json
build.config.js
libs/sil_error_handler/error_handler.js
libs/sil_grid/sil_grid.js
src/app/app.js
src/app/config.js

Add sil error handler

---

src/app/config.js

added sil grid

---

Gruntfile.js

There's a bug in angular annotation

Stop mangling js code in uglify

---

bower.json

Changed acute-select library to use the forked one with changes in
annotation and other fixes

Library Change

---

.jshintrc
build.config.js
karma/karma-unit.tpl.js
package.json
src/app/common/directives/module.js
src/app/common/directives/ui.bootstrap.popover.close.js
src/app/common/tests/ui.bootstrap.popover.close.spec.js
src/app/common/tpls/del-pop.tpl.html
src/app/service_mgmt/tpls/service_edit.options.tpl.html
src/app/setup/tpls/facilities/regulatory_bodies/regulatory-bodies-grid.tpl.html
src/app/users/tpls/profile.contacts.tpl.html
src/app/users/tpls/users.edit.constituencies.tpl.html
src/app/users/tpls/users.edit.contacts.tpl.html
src/app/users/tpls/users.edit.counties.tpl.html
src/app/users/tpls/users.edit.regulatory_body.tpl.html

Changed delete icon times to trash
Created popover close directive
Added bardjs to testing workflow(popover directive is example)
**LOOK AT THE README (https://github.com/wardbell/bardjs)  TO EXPLOIT IT()**
Yet to look at directive in other popovers except for service_options

Popover Close Directive

---

package.json
src/app/common/directives/ui.bootstrap.popover.close.js

Annotated code in popover_close directive

---

Gruntfile.js
src/app/facility_mgmt/tpls/facility_edit.contacts.tpl.html
src/app/facility_mgmt/tpls/facility_edit.tpl.html

Added task for watch that adds the compile task
Added html template for contacts in a facility
Standardized tab headings for editing a facility

Scaffold for facility contacts

---

src/app/facility_mgmt/controllers/edit.js
src/app/facility_mgmt/tpls/facilities.list.tpl.html
src/app/facility_mgmt/tpls/facility_edit.tpl.html

Standard button for list of facilities added
buttons with text for facilities

Hard coded content header edit facility

---

src/app/service_mgmt/tpls/service_edit.basic.tpl.html
src/app/service_mgmt/tpls/service_edit.options.tpl.html
src/app/users/tpls/users.edit.contacts.tpl.html
src/app/users/tpls/users.edit.counties.tpl.html
src/app/users/tpls/users.edit.groups.tpl.html
src/less/basic.less
src/less/card.less
src/less/content.less

…nd restyled master detailed for the same

Fade in transition for multistep forms in users and service

---

src/app/facility_mgmt/controllers/upgrade_downgrade.js
src/app/facility_mgmt/states/upgrade_downgrade.js
src/app/facility_mgmt/tpls/facility_downgrade.tabheaders.tpl.html
src/app/facility_mgmt/tpls/facility_edit.location.tpl.html
src/app/facility_mgmt/tpls/facility_upgrade.tabheaders.tpl.html
src/app/facility_mgmt/tpls/facility_upgrade_downgrade.tabheaders.tpl.html
src/app/facility_mgmt/tpls/facility_upgrade_downgrade.tpl.html

fixed routing issue with facility services

improved style for upgrade and downgrade

---

src/app/dashboard/tpls/content.tpl.html
src/app/users/controllers/users.js
src/app/users/tpls/users.edit.constituencies.tpl.html
src/app/users/tpls/users.edit.tpl.html
src/app/users/tpls/users.list.tpl.html
src/less/alerts.less

still to fix user group assignment issues

fixes in county_admin role ui

---

src/app/setup/controllers/gis.js
src/app/setup/routes/gis.js
src/app/setup/tests/controllers/gis.controllers.spec.js
src/app/setup/tpls/gis/methods.edit.tpl.html
src/app/setup/tpls/gis/sources.edit.tpl.html

Backend pending review of delete functionality

Fixed delete for geo code source and geo code methods

---

src/app/facility_mgmt/controllers/edit.js
src/app/facility_mgmt/controllers/upgrade_downgrade.js
src/app/facility_mgmt/tpls/facility_edit.services.tpl.html
src/app/facility_mgmt/tpls/facility_upgrade_downgrade.tpl.html
src/less/basic.less

Hide and show services in facility upgrade/downgrade

---

src/app/facility_mgmt/controllers/edit.js
src/app/facility_mgmt/tpls/facility_edit.geolocation.tpl.html
src/less/basic.less
src/less/sidebar.less

Adds validation to geolocation tab

---

src/app/common/tpls/revision.list.tpl.html
src/app/setup/controllers/sub_counties.js
src/app/setup/controllers/ward.js
src/app/setup/tpls/constituencies/constituency.details.tpl.html
src/app/setup/tpls/contacts/contact-types-view.tpl.html
src/app/setup/tpls/facilities/job_titles/job-titles-view.tpl.html
src/app/setup/tpls/facilities/owners/facility-owner-types-view.tpl.html
src/app/setup/tpls/facilities/owners/facility-owners-view.tpl.html
src/app/setup/tpls/gis/methods.edit.tpl.html
src/app/setup/tpls/gis/sources.edit.tpl.html
src/app/setup/tpls/sub_counties/sub_counties-grid.tpl.html
src/app/setup/tpls/wards/wards-grid.tpl.html

Layout issues	resolved
Fix job title, at control label.

Minor issues fixes in setup module

---

Gruntfile.js
ci_test.sh
src/app/facility_mgmt/states/approve.js
src/app/facility_mgmt/tpls/body.tpl.html
src/app/reports/controllers/facility_up_down_grades.js
src/app/reports/controllers/module.js
src/app/reports/routes.js
src/app/reports/services.js
src/app/reports/tests/controllers/facility_updowngrade.spec.js
src/app/reports/tpls/facility_changes.tpl.html

Used compiled code in e2e tests
Added permissions for closed facilities

Wired up facility upgrade downgrade

---

src/app/reports/tpls/body.tpl.html
src/app/reports/tpls/facilities.grid.tpl.html
src/app/reports/tpls/facility_changes_view.tpl.html

Wired up detailed view in facility changes
Fix issue with responsiveness

Wired up detailed view in facility changes

---

src/app/reports/tpls/facility_changes.tpl.html
src/app/reports/tpls/facility_constituencies.tpl.html
src/app/reports/tpls/facility_counties.tpl.html
src/app/reports/tpls/facility_counties_constituencies.tpl.html
src/app/reports/tpls/facility_counties_types.tpl.html
src/app/reports/tpls/facility_keph_levels.tpl.html
src/app/reports/tpls/facility_owner_categories.tpl.html
src/app/reports/tpls/facility_owners.tpl.html
src/app/reports/tpls/facility_type_categories.tpl.html
src/app/reports/tpls/facility_types.tpl.html
src/index.html
src/less/colors.less
src/less/main.less

Footer text in smaller devices fixed
Nested tables in reports scale properly in smaller devices

Various fixes related to responsiveness

---

src/app/service_mgmt/tpls/option_group_edit.tpl.html
src/app/setup/controllers/facilities.js
src/app/setup/tests/controllers/regulatorybody.controllers.spec.js
src/app/setup/tpls/dashboard/body.tpl.html
src/app/setup/tpls/facilities/regulatory_bodies/regulatory-bodies-grid.tpl.html
src/app/setup/tpls/facilities/regulatory_bodies/regulatory-bodies-view.tpl.html
src/less/body.less
src/less/content.less
src/less/main.less
src/less/sidebar.less
src/settings.js

Scafolding regulatory body contacts and removing double scrollbars

---

src/app/service_mgmt/tpls/option_group_edit.tpl.html
src/app/setup/controllers/town.js
src/app/setup/tests/e2e/facility_owners.e2e.js
src/app/setup/tests/e2e/optiongroup.e2e.js
src/app/setup/tests/e2e/regulatorybody.e2e.js
src/app/setup/tests/e2e/towns.e2e.js
src/app/setup/tpls/facilities/owners/facility-owners-view.tpl.html

towns
regulating bodies
facility owners
option groups

e2e Testing

---

src/app/dashboard/tpls/content.tpl.html
src/app/setup/controllers/sub_counties.js
src/app/setup/routes/sub_counties.js
src/app/setup/tests/controllers/scounties.controllers.spec.js
src/app/setup/tpls/dashboard/body.tpl.html
src/app/setup/tpls/sub_counties/sub_counties.details.tpl.html

Added sub county permissions
Added delete sub county

Added sub county permissions and sub county delete

---

src/app/facility_mgmt/tpls/facilities.grid.tpl.html
src/app/setup/tpls/facilities/depts/depts-view.tpl.html
src/less/content.less
src/settings.js

Fixing regulatory body select box. Adding back Facility creation button and minor styling

Fixing Facility Department CRUD

---

src/app/facility_mgmt/states/regulate.js
src/app/facility_mgmt/tpls/body.tpl.html
src/app/facility_mgmt/tpls/facilities.list.tpl.html
src/app/facility_mgmt/tpls/facilities.rejected.list.tpl.html
src/app/facility_mgmt/tpls/facility_approved.list.tpl.html
src/app/reports/tpls/bc_constituencies.tpl.html
src/app/reports/tpls/bc_counties.tpl.html
src/app/reports/tpls/bc_wards.tpl.html
src/app/reports/tpls/facilities.grid.tpl.html
src/app/reports/tpls/facility_changes.tpl.html
src/app/reports/tpls/facility_changes_view.tpl.html
src/app/reports/tpls/facility_constituencies.tpl.html
src/app/reports/tpls/facility_counties_constituencies.tpl.html
src/app/setup/tpls/constituencies/constituencies-grid.tpl.html
src/app/setup/tpls/contacts/contact-types-grid.tpl.html
src/app/setup/tpls/counties/constituencies.tpl.html
src/app/setup/tpls/gis/methods.list.tpl.html
src/app/setup/tpls/gis/sources.list.tpl.html
src/app/setup/tpls/sub_counties/sub_counties-grid.tpl.html
src/app/setup/tpls/towns/towns-grid.tpl.html
src/app/setup/tpls/wards/wards-grid.tpl.html
src/app/users/tpls/groups.list.tpl.html
src/app/users/tpls/users.list.tpl.html

Added messages when there is no data
Removed unnecessary links
Merge master into branch

Added messages when there is no data in the grids

---

src/app/dashboard/tpls/content.tpl.html
src/app/facility_mgmt/tpls/facility_approve.services.tpl.html
src/app/facility_mgmt/tpls/facility_approve.tpl.html
src/app/facility_mgmt/tpls/facility_approve.units.tpl.html
src/app/facility_mgmt/tpls/facility_print.tpl.html
src/app/facility_mgmt/tpls/facility_services.edit.tpl.html

…fault during facility creation

Fixing facility department name not being displayed 

---

src/app/facility_mgmt/controllers/edit.js
src/settings.js

When saving basic details officer contacts all cleared

---

src/app/chul/controllers/list.js
src/app/chul/tpls/chul.list.tpl.html
src/app/chul/tpls/chul_view.tpl.html
src/settings.js

Added location fields in CU grid as well as the read only view for CUs

Putting up CU readonly view

---

src/app/facility_mgmt/states/approve.js
src/app/facility_mgmt/tpls/body.tpl.html
src/app/facility_mgmt/tpls/facilities_pending.grid.tpl.html
src/app/facility_mgmt/tpls/facilities_pending.list.tpl.html
src/app/facility_mgmt/tpls/facilities_pending.view.tpl.html

Will help SCHRIO roles know if updates have been added into the facility details

Added pending update view for SCHRIO

---

src/app/setup/controllers/ward.js
src/app/setup/tests/controllers/wards.controller.spec.js
src/app/setup/tpls/wards/edit_ward.tpl.html

Autopopulating county name in ward editing

---

src/app/facility_mgmt/tpls/facility_approve.services.tpl.html
src/app/facility_mgmt/tpls/facility_print.tpl.html
src/app/facility_mgmt/tpls/regulator_sync.list.tpl.html
src/app/users/tpls/users.edit.tpl.html

Fixes responsiveness in smaller devices for facilities
Fixes responsiveness in regulation sync list in smaller devices

Fixes responsive issues

---

ci_test.sh
e2e/protractor.conf.js
karma/karma-unit.tpl.js
src/app/common/tests/utils.e2e.js
src/app/facility_mgmt/tests/e2e/create_facility.e2e.js
src/app/facility_mgmt/tpls/facility_services.view.tpl.html
src/app/reports/controllers/facilities.js
src/app/reports/tests/e2e/bc_constituencies.e2e.js
src/app/reports/tests/e2e/bc_counties.e2e.js
src/app/reports/tests/e2e/bc_wards.e2e.js
src/app/reports/tests/e2e/facility_constituencies.e2e.js
src/app/reports/tests/e2e/facility_counties.e2e.js
src/app/reports/tests/e2e/facility_county_constituencies.e2e.js
src/app/reports/tests/e2e/facility_county_keph_levels.e2e.js
src/app/reports/tests/e2e/facility_owner_categories.e2e.js
src/app/reports/tests/e2e/facility_owners.e2e.js
src/app/reports/tests/e2e/facility_types.e2e.js
src/app/setup/tests/e2e/categories.e2e.js
src/app/setup/tests/e2e/contacts.e2e.js
src/app/setup/tests/e2e/facility_job_titles.e2e.js
src/app/setup/tests/e2e/facility_keph_levels.e2e.js
src/app/setup/tests/e2e/facility_owner_categories.e2e.js
src/app/setup/tests/e2e/facility_owners.e2e.js
src/app/setup/tests/e2e/facility_reasons.e2e.js
src/app/setup/tests/e2e/gis_methods.e2e.js
src/app/setup/tests/e2e/gis_sources.e2e.js
src/app/setup/tests/e2e/optiongroup.e2e.js
src/app/setup/tests/e2e/regulatorybody.e2e.js
src/app/setup/tests/e2e/sub_counties.e2e.js
src/app/setup/tests/e2e/towns.e2e.js

enable e2e tests on circleci
make timeouts env-configurable

revive e2e tests

---

src/app/facility_mgmt/tpls/facility_approve.units.tpl.html

scope binding changed from department_name to unit_name

scope binding changed from department_name to unit_name

---

bower.json
ci_test.sh
package.json

e2e in saucelabs take too long, a better way may be required

bump version to 0.0.1a34, disable saucelabs e2e

---

Gruntfile.js
LICENSE
src/app/chul/tpls/chul_basic.tpl.html
src/app/facility_mgmt/tpls/facility_approve.tpl.html

Fix on facilty approve/reject comment text

Fixes text on chu location to area of coverage

---

src/app/chul/tpls/chul_basic.tpl.html
src/app/common/tpls/header.tpl.html

Fixed placeholder typo in chu name textbox

Renamed tab to Community Health Unit

---

src/app/auth/controllers.js
src/app/auth/services.js
src/app/auth/tests/controllers.spec.js
src/app/auth/tests/services.spec.js
src/app/config.js

starts Idle watches if user is logged in
restore page title as part of starting timeout

fix timeout messages

---

src/app/common/tpls/header.tpl.html

It is system configuration officer only who should see system setup

Ensure national admin does not see system setup

---

src/app/facility_mgmt/controllers/edit.js
src/app/facility_mgmt/states/edit.js
src/app/facility_mgmt/tests/controllers/edit.spec.js
src/app/facility_mgmt/tpls/facilities.closed.list.tpl.html
src/app/facility_mgmt/tpls/facility_edit.basic.tpl.html
src/app/facility_mgmt/tpls/facility_edit_open.tpl.html
src/app/facility_mgmt/tpls/facility_view.tpl.html

Various Fixes

---

src/app/common/tpls/header.tpl.html

Make sure only sys admin sees the system setup

System setup hot fix
